container_type: DockerImage
image: mlcommons/medperf-step-cli:0.0.2
tasks:
  get_client_cert:
    run_args:
      command: /project/get_cert.sh get_client_cert
    input_volumes:
      ca_config:
        mount_path: /mlcommons/volumes/ca_config/ca_config.json
        type: file
    output_volumes:
      pki_assets:
        mount_path: /mlcommons/volumes/pki_assets
        type: directory
  get_server_cert:
    run_args:
      command: /project/get_cert.sh get_server_cert
    input_volumes:
      ca_config:
        mount_path: /mlcommons/volumes/ca_config/ca_config.json
        type: file
    output_volumes:
      pki_assets:
        mount_path: /mlcommons/volumes/pki_assets
        type: directory
  trust:
    run_args:
      command: /project/trust.sh
    input_volumes:
      ca_config:
        mount_path: /mlcommons/volumes/ca_config/ca_config.json
        type: file
    output_volumes:
      pki_assets:
        mount_path: /mlcommons/volumes/pki_assets
        type: directory
  verify_cert:
    run_args:
      command: /project/verify_cert.sh
    input_volumes:
      ca_config:
        mount_path: /mlcommons/volumes/ca_config/ca_config.json
        type: file
    output_volumes:
      pki_assets:
        mount_path: /mlcommons/volumes/pki_assets
        type: directory
